
["Chunk settings"]
	#How long a player can keep chunkloaded chunks active after logging out. Default: 10 min
	#Range: 0 ~ 2000
	chunkunloadnoplayer = 360
	#Print log messages for which chunk tickets are unloaded where. Default: false
	debugmessage = true
	#List of excluded ticket/chunkload types, these are mod-specific. : e.g. format :  ["mekanism", "player"]
	excludedtickets = []

